### ISSUE TITLE
Question About the Results

### ISSUE THREAD

**Issue by NoviScl** [shmsw25/AmbigQA#15]
Hi Sewon,

For the provided checkpoint named "DPR Reader trained on AmbigNQ (387M)", is it trained just on the AmbigNQ training set or NQ + AmbigNQ training set? I tried to train a DPR Reader with BERT-base span extractor on AmbigNQ training set alone and the result I got seems to be lower than the provided checkpoint. 

Best,
Chenglei

**Comment by shmsw25** [comment]
Hi @NoviScl, yeah you are right, it is pretrained on NQ and then trained on AmbigNQ. Sorry that it wasn't super clear.
