### ISSUE TITLE
About {train|dev|test}_id2answers.json

### ISSUE THREAD

**Issue by Yifan-Gao** [shmsw25/AmbigQA#6]
Hi @shmsw25 , I notice you mentioned two versions of NQ answers in README, and `{train|dev|test}_id2answers.json` files are answers released by google. However, I check [answers](https://github.com/efficientqa/nq-open) in the original version and find that in some cases, they are different from your released files. In some cases, answers in `{train|dev|test}_id2answers.json` are empty strings but non-empty in the original version.

**Comment by shmsw25** [comment]
Hi @Yifan-Gao,
You are right, it seems like there were issues with answers that contain special characters. I've fixed the error and verified that all answers have 1-1 mapping with the answers released by Google. Updated files are available in the same url ([train][train]|[dev][dev]|[test][test]).
Sorry about the confusion and thanks for reporting!

[train]: https://nlp.cs.washington.edu/ambigqa/data/train_id2answers.json
[dev]: https://nlp.cs.washington.edu/ambigqa/data/dev_id2answers.json
[test]: https://nlp.cs.washington.edu/ambigqa/data/test_id2answers.json

**Comment by Yifan-Gao** [comment]
Thanks!
