### ISSUE TITLE
Error while creating passage vectors

### ISSUE THREAD

**Issue by abhinavbh08** [shmsw25/AmbigQA#7]
Hi @shmsw25  , while running the command, 
`for i in 0 1 2 3 4 5 6 7 8 9 ; do \ # for parallelization
  python3 cli.py --do_predict --bert_name bert-base-uncased --output_dir out/dpr --do_predict --task dpr --predict_batch_size 3200 --db_index $i \
done`
One error is coming,  `assert args.bert_name=="bart-large"`, in PassageData.py . 
Can you please help ?

**Comment by shmsw25** [comment]
Oops, looks like I forgot to delete lines for debugging. Sorry about that, it should be working now. Thanks for reporting!
