### ISSUE TITLE
In BART generation, attention_mask is not aligned with input_id

### ISSUE THREAD

**Issue by Yifan-Gao** [shmsw25/AmbigQA#8]
https://github.com/shmsw25/AmbigQA/blob/74f9ff85da81bd2925fca2ddb6ea59437335631b/codes/Data.py#L201-L217

After line 207, I think the `attention_mask` should also be cropped as `attention_mask[idx] = curr_attention_mask[:end_of_question]`. Otherwise, it will not be aligned with `input_ids`.

**Comment by shmsw25** [comment]
You are right, thanks for catching it! Fixed it now.

**Comment by Yifan-Gao** [comment]
thanks!
